# -*- coding: utf-8 -*-
"""Task_01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j5fkN6JCy-ZvTzElOfLmAbSz3wbniUhy
"""

!pip install transformers
!pip install datasets

import os
from transformers import AutoModelForCausalLM, AutoTokenizer, TextDataset, DataCollatorForLanguageModeling
from transformers import Trainer, TrainingArguments
from datasets import load_dataset

print("\nDownloading H.P. Lovecraft text...")
!wget https://www.gutenberg.org/files/50133/50133-0.txt -O lovecraft.txt
file_path = 'lovecraft.txt'
print(f"✅ Data saved to {file_path}")

print("\nLoading pre-trained GPT-2 model and tokenizer...")
model_name = "gpt2"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(model_name)
print("✅ Model and tokenizer loaded.")

print("\nPreparing dataset for training...")
# Special token to handle end-of-text
tokenizer.pad_token = tokenizer.eos_token

train_dataset = TextDataset(
    tokenizer=tokenizer,
    file_path=file_path,
    block_size=128  # Process the text in chunks of 128 tokens
)

data_collator = DataCollatorForLanguageModeling(
    tokenizer=tokenizer,
    mlm=False # Masked Language Modeling is not needed for GPT-2
)
print("✅ Dataset is ready.")

print("\nConfiguring training...")
training_args = TrainingArguments(
    output_dir="./gpt2-lovecraft", # Directory to save the new model
    overwrite_output_dir=True,
    num_train_epochs=1,           # One loop through the data is a good start
    per_device_train_batch_size=8,
    save_steps=500,
    save_total_limit=2,
)

trainer = Trainer(
    model=model,
    args=training_args,
    data_collator=data_collator,
    train_dataset=train_dataset,
)

print("\nStarting fine-tuning... (This will take several minutes)")
trainer.train()
print("✅ Fine-tuning complete!")

print("\n--- Generating text from the new Lovecraftian model ---")
prompt = "In a realm of cosmic horror,"
input_ids = tokenizer(prompt, return_tensors="pt").input_ids

# Move input_ids to the same device as the model
input_ids = input_ids.to(model.device)

# We use our fine-tuned 'model' to generate text
generated_output = model.generate(
    input_ids,
    max_length=150,
    num_return_sequences=1,
    temperature=0.8, # A little more creative
    top_k=50,
    do_sample=True # This enables sampling-based generation
)

# Decode and print the result
generated_text = tokenizer.decode(generated_output[0], skip_special_tokens=True)
print("\nGenerated Text:")
print(generated_text)